import { createServer } from 'vite';
import { spawn } from 'node:child_process';
import electron from 'electron';
await import('./build-electron.mjs');
const server = await createServer();
await server.listen();
const env = { ...process.env, WIKI_DEV_URL: 'http://127.0.0.1:5187/' };
delete env.ELECTRON_RUN_AS_NODE;
const child = spawn(electron, ['.'], { stdio: 'inherit', env });
const handleExit = async () => { child.kill(); await server.close(); };
process.on('SIGINT', handleExit);
process.on('SIGTERM', handleExit);
child.on('exit', async code => { await server.close(); process.exit(code || 0); });
