import { _electron as electron, expect } from '@playwright/test';
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const directory = await mkdtemp(join(tmpdir(), 'wiki-smoke-'));
const fixture = join(directory, 'fixture-cli');
await writeFile(fixture, `#!/usr/bin/env node
const fs = require('node:fs');
let input = '';
process.stdin.on('data', chunk => input += chunk);
process.stdin.on('end', () => {
 fs.appendFileSync(${JSON.stringify(join(directory, 'calls'))}, 'called\\n');
 setTimeout(() => fs.writeFileSync(process.argv[process.argv.indexOf('--output-last-message') + 1], '## 테스트 요약\\n\\n- 금요일에 회의를 진행합니다.'), 500);
});
`, { mode: 0o700 });
await mkdir(join(directory, 'Vault', '.wiki'), { recursive: true });
await writeFile(join(directory, 'Vault', '.wiki', 'settings.json'), JSON.stringify({ provider: 'codex', codexPath: fixture, claudePath: '', model: '', captureShortcut: '', quickNoteShortcut: '', customInstruction: '정리해 주세요.' }));
const app = await electron.launch({ args: [resolve('.')], env: { ...process.env, WIKI_DATA_DIR: directory } });
const errors = [];
// CDP keyboard events bypass Electron before-input-event. Exercise native app bindings through webContents.
const handleNativeKey = async (keyCode, modifiers = ['meta']) => app.evaluate(({ BrowserWindow }, { keyCode, modifiers }) => {
 const contents = BrowserWindow.getAllWindows()[0].webContents;
 contents.sendInputEvent({ type: 'keyDown', keyCode, modifiers });
 contents.sendInputEvent({ type: 'keyUp', keyCode, modifiers });
}, { keyCode, modifiers });
try {
 const page = await app.firstWindow();
 page.on('pageerror', error => errors.push(error.message));
 await page.waitForFunction(() => !!window.wiki);
 expect(await page.evaluate(async () => (await window.wiki.handleBootstrap()).settings.model)).toBe('gpt-5.6-luna');
 await page.getByRole('button', { name: /새 메모 만들기/ }).click();
 await page.getByRole('button', { name: /빈 메모/ }).click();
 await page.getByLabel('메모 제목').fill('금요일 회의');
 await page.getByLabel('메모 내용').fill('금요일에 회의를 진행합니다.');
 await expect(page.getByText('저장됨', { exact: true })).toBeVisible();
 await expect(page.getByLabel('메모 검색')).toBeVisible();
 await page.getByLabel('메모 검색').fill('없는 제목');
 await expect(page.getByText('검색 결과가 없어요')).toBeVisible();
 await page.getByLabel('검색 지우기').click();
 await page.getByLabel('메모 내용').click();
 await handleNativeKey('K');
 await expect(page.getByLabel('메모 검색')).toBeFocused();
 await expect(async () => { let calls = ''; try { calls = await readFile(join(directory, 'calls'), 'utf8'); } catch {} expect(calls).toBe(''); }).toPass();
 await page.getByRole('button', { name: '요약하기', exact: true }).click();
 await expect(page.getByText('요약하기 중…')).toBeVisible();
 await expect(page.locator('.wiki__ai-result')).toContainText('테스트 요약');
 await page.getByRole('button', { name: '본문 아래에 추가' }).click();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByLabel('메모 내용')).toBeFocused();
 await expect(page.getByLabel('메모 내용')).toHaveValue(/AI 정리/);
 await page.getByTitle('메모 고정').click();
 await page.getByRole('button', { name: /고정한 메모/ }).click();
 await expect(page.locator('.wiki__note-row')).toHaveCount(1);
 await page.getByTitle('설정', { exact: true }).click();
 await page.getByLabel('동작 1', { exact: true }).selectOption('capture');
 await page.getByLabel('실행 범위 1', { exact: true }).selectOption('global');
 await page.getByLabel('단축키 1', { exact: true }).click();
 await page.keyboard.press('Meta+Alt+9');
 await expect(page.getByLabel('단축키 1', { exact: true })).toHaveValue('⌘ ⌥ 9');
 await page.getByRole('button', { name: '설정 저장' }).click();
 expect(await app.evaluate(({ globalShortcut }) => globalShortcut.isRegistered('Command+Alt+9'))).toBe(true);
 await page.getByTitle('설정', { exact: true }).click();
 await expect(page.getByLabel('모델', { exact: true })).toHaveValue('gpt-5.6-luna');
 await page.getByLabel('AI 연결 방식').selectOption('openai');
 await expect(page.getByLabel('모델', { exact: true })).toHaveValue('gpt-5-nano');
 await expect(page.getByLabel('OpenAI API 키')).toHaveAttribute('type', 'password');
 await page.getByLabel('AI 연결 방식').selectOption('codex');
 await page.getByRole('button', { name: '단축키 추가', exact: true }).click();
 await page.getByLabel('단축키 6', { exact: true }).click();
 await page.keyboard.press('Meta+k');
 await page.getByRole('button', { name: '설정 저장' }).click();
 await expect(page.locator('.wiki__settings').getByRole('status')).toContainText('같은 단축키');
 expect(await app.evaluate(({ globalShortcut }) => globalShortcut.isRegistered('Command+Alt+9'))).toBe(true);
 await page.getByLabel('단축키 6', { exact: true }).click();
 await page.keyboard.press('Meta+Alt+j');
 await page.getByLabel('단축키 6', { exact: true }).click();
 await page.keyboard.press('Escape');
 await expect(page.getByLabel('단축키 6', { exact: true })).toHaveValue('⌘ ⌥ J');
 await page.getByRole('button', { name: '단축키 추가', exact: true }).click();
 await page.getByLabel('단축키 7', { exact: true }).click();
 await page.keyboard.press('Meta+Alt+l');
 await page.getByLabel('단축키 7', { exact: true }).click();
 await page.keyboard.press('Backspace');
 await expect(page.getByLabel('단축키 7', { exact: true })).toHaveValue('');
 await page.getByRole('button', { name: '사용자 동작 추가', exact: true }).click();
 await page.getByLabel('사용자 동작 이름 1').fill('할 일 추출');
 await page.getByLabel('사용자 동작 요청 1').fill('메모에서 할 일을 체크리스트로 정리해 주세요.');
 await page.screenshot({ path: join(directory, 'settings.png') });
 await page.getByRole('button', { name: '설정 저장' }).click();
 await page.getByLabel('메모 내용').click();
 await handleNativeKey('J', ['meta', 'alt']);
 await expect(page.getByLabel('메모 검색')).toBeFocused();
 await handleNativeKey('P', ['meta', 'shift']);
 await page.getByLabel('명령 또는 메모 검색').fill('할 일 추출');
 await page.keyboard.press('Enter');
 await expect(page.locator('.wiki__ai-result')).toContainText('테스트 요약');
 await page.getByRole('dialog').getByLabel('닫기').click();
 await page.getByRole('button', { name: '미리보기' }).click();
 await expect(page.locator('.wiki__markdown')).toContainText('테스트 요약');
 await page.locator('.wiki__new-note').click();
 await page.getByRole('button', { name: /빈 메모/ }).click();
 await page.getByRole('button', { name: 'AI로 작성·정리' }).click();
 await expect(page.getByRole('button', { name: '초안 작성', exact: true })).toBeDisabled();
 await page.getByLabel('AI에게 작성 요청').fill('주간 회의 체크리스트를 작성해 줘');
 await page.getByRole('button', { name: '초안 작성', exact: true }).click();
 await expect(page.getByText('초안 작성 중…')).toBeVisible();
 await expect(page.getByRole('button', { name: '본문에 추가됨' })).toBeDisabled();
 await page.getByRole('dialog').getByLabel('닫기').click();
 if (await page.getByRole('button', { name: '편집하기', exact: true }).count()) await page.getByRole('button', { name: '편집하기', exact: true }).click();
 await expect(page.getByLabel('메모 내용')).toHaveValue(/^## 테스트 요약/);
 const originalBody = await page.getByLabel('메모 내용').inputValue();
 await page.getByRole('button', { name: 'AI로 작성·정리' }).click();
 await page.getByLabel('AI에게 작성 요청').fill('후속 작업 초안을 작성해 줘');
 await page.getByRole('button', { name: '초안 작성', exact: true }).click();
 await expect(page.getByRole('button', { name: '본문 아래에 추가' })).toBeEnabled();
 await page.getByRole('dialog').getByLabel('닫기').click();
 await expect(page.getByLabel('메모 내용')).toHaveValue(originalBody);
 await page.getByLabel('메모 검색').fill('기존 검색어');
 await page.getByRole('button', { name: 'AI로 작성·정리' }).click();
 await handleNativeKey('K');
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByLabel('메모 검색')).toBeFocused();
 await page.keyboard.insertText('금요일');
 await expect(page.getByLabel('메모 검색')).toHaveValue('금요일');
 await page.keyboard.press('Enter');
 await expect(page.getByLabel('메모 내용')).toBeFocused();
 await app.evaluate(({ Menu }) => {
   const item = Menu.getApplicationMenu().items.flatMap(item => item.submenu?.items || []).find(item => item.label === '메모 검색');
   item.click();
 });
 await expect(page.getByLabel('메모 검색')).toBeFocused();
 await page.getByRole('button', { name: '폴더 추가', exact: true }).click();
 await page.getByLabel('폴더 이름', { exact: true }).fill('연결 실험');
 await page.getByRole('button', { name: '폴더 저장', exact: true }).click();
 await expect(page.getByLabel('메모 폴더', { exact: true })).toContainText('연결 실험');
 await page.getByLabel('메모 폴더', { exact: true }).selectOption('연결 실험');
 await expect(page.getByText('저장됨', { exact: true })).toBeVisible();
 await page.getByLabel('메모 제목').fill('연결 대상');
 await expect(page.getByText('저장됨', { exact: true })).toBeVisible();
 await page.locator('.wiki__new-note').click();
 await page.getByRole('button', { name: /빈 메모/ }).click();
 await page.getByLabel('메모 제목').fill('링크 테스트');
 await page.getByLabel('메모 내용').fill('참고: [[');
 await expect(page.getByRole('listbox', { name: '연결할 문서' })).toBeVisible();
 await page.getByRole('option', { name: /연결 대상/ }).click();
 await expect(page.getByLabel('메모 내용')).toHaveValue('참고: [[연결 실험/연결 대상]]');
 await page.getByRole('button', { name: '미리보기', exact: true }).click();
 await page.locator('.wiki__inline__link').click();
 await expect(page.getByLabel('메모 제목')).toHaveValue('연결 대상');
 await page.getByLabel('연결 실험 폴더 이름 변경').click();
 await page.getByLabel('폴더 이름', { exact: true }).fill('지식 정원');
 await page.getByRole('button', { name: '폴더 저장', exact: true }).click();
 await expect(page.getByLabel('메모 폴더', { exact: true })).toHaveValue('지식 정원');
 await page.getByRole('button', { name: '명령 팔레트', exact: true }).click();
 await page.getByLabel('명령 또는 메모 검색').fill('링크 테스트');
 await page.keyboard.press('Enter');
 await page.locator('.wiki__inline__link').click();
 await expect(page.getByLabel('메모 제목')).toHaveValue('연결 대상');
 await page.getByLabel('지식 정원 폴더 삭제').click();
 await page.getByRole('button', { name: '폴더 삭제 확인' }).click();
 await expect(page.getByLabel('메모 폴더', { exact: true })).toHaveValue('미분류');
 // Check long Markdown scroll with actual wheel input.
 if (await page.getByRole('button', { name: '편집하기', exact: true }).count()) await page.getByRole('button', { name: '편집하기', exact: true }).click();
 await page.getByLabel('메모 내용').fill(Array.from({ length: 90 }, (_, i) => '## 항목 ' + i + '\n\n긴 문서 테스트입니다.').join('\n\n'));
 await page.getByRole('button', { name: '미리보기', exact: true }).click();
 await page.locator('.wiki__markdown').hover();
 await page.mouse.wheel(0, 900);
 await expect.poll(() => page.locator('.wiki__markdown').evaluate(el => el.scrollTop)).toBeGreaterThan(100);
 await page.screenshot({ path: join(directory, 'app.png') });
 await page.getByTitle('휴지통으로 이동').click();
 await page.getByRole('button', { name: '휴지통', exact: true }).click();
 await expect(page.locator('.wiki__trash-card')).toHaveCount(1);
 await expect(page.locator('.wiki__trash-card p').first()).not.toBeEmpty();
 await page.screenshot({ path: join(directory, 'trash.png') });
 await page.getByRole('button', { name: '영구 삭제', exact: true }).click();
 await page.getByRole('button', { name: '취소', exact: true }).click();
 await expect(page.locator('.wiki__trash-card')).toHaveCount(1);
 await page.getByRole('button', { name: '복원', exact: true }).click();
 await expect(page.getByText('휴지통이 비어 있어요', { exact: true })).toBeVisible();
 await page.getByRole('dialog').getByLabel('닫기').click();
 await page.getByTitle('휴지통으로 이동').click();
 await page.getByRole('button', { name: '휴지통', exact: true }).click();
 await page.getByRole('button', { name: '영구 삭제', exact: true }).click();
 await page.getByRole('button', { name: '영구 삭제 확인', exact: true }).click();
 await expect(page.getByText('휴지통이 비어 있어요', { exact: true })).toBeVisible();
 expect(errors).toEqual([]);
 console.log(JSON.stringify({ passed: true, checks: ['search filtering', 'Cmd+K focus and select from dialog', 'native search menu', 'Enter opens search result', 'AI only on click', 'CLI result and apply', 'prompt generation into blank memo', 'pin filter', 'custom shortcut registration', 'Markdown preview', 'no renderer errors'], screenshot: join(directory, 'app.png') }));
} finally { await app.close(); }
